apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterVersion
metadata:
  name: llm-gpt2
  labels:
    {{- include "llm.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: llm
  componentVersions:
    - componentDefRef: llm
      versionsContext:
        initContainers:
          - name: model
            image: lynnleelhl/gpt2:latest
        containers:
          - name: torchserve
            image:  {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository}}:{{ default .Chart.AppVersion .Values.image.tag }}
            env:
              - name: MODEL_NAME
                value: "gpt2"

---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterVersion
metadata:
  name: llm-baichuan
  labels:
    {{- include "llm.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: llm
  componentVersions:
    - componentDefRef: llm
      configSpecs:
        - name: llm-ts-handler-config-baichuan
          templateRef: llm-ts-handler-config-baichuan
          volumeName: ts-handler-config
          namespace: {{ .Release.Namespace }}
      versionsContext:
        initContainers:
          - name: model
            image: lynnleelhl/baichuan:latest
        containers:
          - name: torchserve
            image:  {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository}}:{{ default .Chart.AppVersion .Values.image.tag }}
            env:
              - name: MODEL_NAME
                value: "baichuan"
              - name: TSH_MODEL_KWARGS
                value: /llm/ts-handler-config/model_kwargs.py
              - name: TSH_TOKENIZER_KWARGS
                value: /llm/ts-handler-config/tokenizer_kwargs.py
