apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: llm
  labels:
    {{- include "llm.labels" . | nindent 4}}
spec:
  componentDefs:
    - name: llm
      workloadType: Stateless
      characterType: llm
      monitor:
        builtIn: false
        exporterConfig:
          scrapePath: /metrics
          scrapePort: 8082
      configSpecs:
        - name: llm-config-template
          templateRef: llm-config-template
          volumeName: config
          namespace: {{ .Release.Namespace }}
      scriptSpecs:
        - name: llm-scripts
          templateRef: llm-scripts
          namespace: {{ .Release.Namespace }}
          volumeName: scripts
          defaultMode: 493
      service:
        ports:
          - name: ts
            port: 8080
            targetPort: ts
          - name: ts-management
            port: 8081
            targetPort: ts-management
          - name: ts-metrics
            port: 8082
            targetPort: ts-metrics
      podSpec:
        volumes:
          - name: model-store
            emptyDir: {}
        initContainers:
          - name: model
            # TODO: CT move to cv
            image: lynnleelhl/gpt2:latest
            imagePullPolicy: {{default .Values.image.pullPolicy "IfNotPresent"}}
            command:
              - /bin/sh
              - -c
              - cp /model_store/* /llm/storage/
            securityContext:
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /llm/storage
                name: model-store
        containers:
          - name: llm
            imagePullPolicy: {{default .Values.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /llm/config/
                name: config
              - name: scripts
                mountPath: /scripts
              - mountPath: /llm/storage
                name: model-store
            command:
              - /scripts/start.sh
            ports:
              - name: ts
                containerPort: 8080
              - name: ts-management
                containerPort: 8081
              - name: ts-metrics
                containerPort: 8082
            startupProbe:
              failureThreshold: 18
              httpGet:
                path: /ping
                port: ts
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /ping
                port: ts
                scheme: HTTP
              periodSeconds: 15
              successThreshold: 1
              timeoutSeconds: 10
            readinessProbe:
              failureThreshold: 18
              httpGet:
                path: /ping
                port: ts
                scheme: HTTP
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 3
  connectionCredential:
    username: root
    password: ""