apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: llm
  labels:
    {{- include "llm.labels" . | nindent 4}}
spec:
  type: etcd
  componentDefs:
    - name: llm
      workloadType: Stateless
      characterType: llm
      monitor:
        builtIn: false
        exporterConfig:
          scrapePath: /metrics
          scrapePort: 8082
      configSpecs:
        - name: llm-config-template
          templateRef: llm-config-template
          volumeName: config
          namespace: {{ .Release.Namespace }}
      service:
        ports:
          - name: ts
            port: 8080
            targetPort: ts
          - name: ts-management
            port: 8081
            targetPort: ts-management
          - name: ts-metrics
            port: 8082
            targetPort: ts-metrics
      podSpec:
        volumes:
          - name: model-store
            emptyDir: {}
        initContainers:
          - name: model
            image: lynnleelhl/gpt2:latest
            imagePullPolicy: {{default .Values.image.pullPolicy "IfNotPresent"}}
            command:
              - /bin/sh
              - -c
              - cp /model_store/* /llm/storage/
            securityContext:
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /llm/storage
                name: model-store
        containers:
          - name: llm
            imagePullPolicy: {{default .Values.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /llm/config/
                name: config
              - mountPath: /llm/storage
                name: model-store
            command:
              - /bin/sh
              - -c
              - |
                cp /llm/config/config.properties /config.properties
                sed -i "s/KB_LLM_MODEL_NAME_PLACEHOLDER/${MODEL_NAME}/g" /config.properties
                echo "running config:"
                cat /config.properties
                torchserve --start --foreground --model-store /llm/storage --ts-config /config.properties
            ports:
              - name: ts
                containerPort: 8080
              - name: ts-management
                containerPort: 8081
              - name: ts-metrics
                containerPort: 8082
  connectionCredential:
    username: root
    password: ""