apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: nebula
  labels:
    {{- include "nebula.labels" . | nindent 4 }}
spec:
  connectionCredential:
    username: root
    password: "$(RANDOM_PASSWD)"
    endpoint: "$(SVC_FQDN):$(SVC_PORT_tcp-nebula)"
    host: "$(SVC_FQDN)"
    port: "$(SVC_PORT_tcp-nebula)"
    accesskey: ""
    secretkey: ""
  componentDefs:
    - name: nebula-console
      workloadType: Stateless
      characterType: nebula
      componentRef:
        - componentDefName: nebula-storaged
          headlessServiceRef:
            - portName: thrift
              containerName: nebula-storaged
              envName: NEBULA_STORAGED_SVC
              format: '{{`ADD HOSTS "{{ .FQDN }}.cluster.local":{{ .Port }}`}}'
              joinWith: ";"
        - componentDefName: nebula-graphd
          serviceRef:
            - name: thrift
              envName: NEBULA_GRAPHD_SVC
      podSpec:
        containers:
          - name: nebula-console
            imagePullPolicy: {{default .Values.nebula.metad.image.pullPolicy "IfNotPresent"}}
            command: ["/bin/sh"]
            args: ["-c", "trap : TERM INT; sleep infinity & wait"]
            lifecycle:
              postStart:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - |
                      echo "Waiting for graphd service $NEBULA_GRAPHD_SVC_NAME to be ready..."
                      until /usr/local/bin/nebula-console --addr $NEBULA_GRAPHD_SVC_NAME --port $NEBULA_GRAPHD_SVC_PORT --user root --password nebula -e "show spaces"; do sleep 2; done
                      echo "graphd service is ready, add storaged address..."
                      touch /tmp/storaged-hosts
                      echo $NEBULA_STORAGED_SVC >> /tmp/storaged-hosts
                      exec /usr/local/bin/nebula-console --addr $NEBULA_GRAPHD_SVC_NAME --port $NEBULA_GRAPHD_SVC_PORT --user root --password nebula -f /tmp/storaged-hosts
                      echo "Start Console succeeded!"
    - name: nebula-metad
      configSpecs:
        - name: nebula-metad-config
          templateRef: nebula-metad-config-template
          namespace: {{ .Release.Namespace }}
          volumeName: nebula-metad
      workloadType: Stateful
      characterType: nebula-metad
      componentRef:
        - componentDefName: nebula-metad
          headlessServiceRef:
            - portName: thrift
              containerName: nebula-metad
              envName: NEBULA_METAD_SVC
              format: '{{`{{ .FQDN }}.cluster.local:{{ .Port }}`}}'
              joinWith: ","
      podSpec:
        containers:
          - name: nebula-metad
            command:
              - /bin/bash
              - -c
              - |
                set -ex
                exec /usr/local/nebula/bin/nebula-metad --flagfile=/usr/local/nebula/etc/nebula-metad.conf --meta_server_addrs=$NEBULA_METAD_SVC --local_ip=$KB_POD_FQDN".cluster.local"  --daemonize=false
            imagePullPolicy: {{default .Values.nebula.metad.image.pullPolicy "IfNotPresent"}}
            ports:
            - containerPort: 9559
              name: thrift
              protocol: TCP
            - containerPort: 19559
              name: http
              protocol: TCP
            - containerPort: 19560
              name: http2
              protocol: TCP
            # readinessProbe:
            #   failureThreshold: 3
            #   httpGet:
            #     path: /status
            #     port: http
            #     scheme: HTTP
            #   initialDelaySeconds: 10
            #   periodSeconds: 10
            #   successThreshold: 1
            #   timeoutSeconds: 5
            volumeMounts:
              - mountPath: /usr/local/nebula/data
                name: data
              - mountPath: /usr/local/nebula/logs
                name: logs
              - mountPath: /usr/local/nebula/etc
                name: nebula-metad
    - name: nebula-graphd
      configSpecs:
        - name: nebula-graphd-config
          templateRef: nebula-graphd-config-template
          namespace: {{ .Release.Namespace }}
          volumeName: nebula-graphd
      workloadType: Stateful
      characterType: nebula-graphd
      service:
        ports:
          - name: thrift
            port: 9669
            targetPort: thrift
            protocol: TCP
          - name: http
            port: 19669
            targetPort: http
            protocol: TCP
          - name: http2
            port: 19670
            targetPort: http2
            protocol: TCP
      componentRef:
        - componentDefName: nebula-metad
          headlessServiceRef:
            - portName: thrift
              containerName: nebula-metad
              envName: NEBULA_METAD_SVC
              format: '{{`{{ .FQDN }}.cluster.local:{{ .Port }}`}}'
              joinWith: ","
      podSpec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: nebula-graphd
            command:
              - /bin/bash
              - -c
              - |
                set -ex
                exec /usr/local/nebula/bin/nebula-graphd --flagfile=/usr/local/nebula/etc/nebula-graphd.conf --meta_server_addrs=$NEBULA_METAD_SVC --local_ip=$KB_POD_FQDN".cluster.local" --daemonize=false
            imagePullPolicy: {{default .Values.nebula.graphd.image.pullPolicy "IfNotPresent"}}
            ports:
            - containerPort: 9669
              name: thrift
              protocol: TCP
            - containerPort: 19669
              name: http
              protocol: TCP
            - containerPort: 19670
              name: http2
              protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /status
                port: http
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            volumeMounts:
              - mountPath: /usr/local/nebula/data
                name: data
              - mountPath: /usr/local/nebula/logs
                name: logs
              - mountPath: /usr/local/nebula/etc
                name: nebula-graphd
    - name: nebula-storaged
      configSpecs:
        - name: nebula-storaged-config
          templateRef: nebula-storaged-config-template
          namespace: {{ .Release.Namespace }}
          volumeName: nebula-storaged
      workloadType: Stateful
      characterType: nebula-storaged
      componentRef:
        - componentDefName: nebula-metad
          headlessServiceRef:
            - portName: thrift
              containerName: nebula-metad
              envName: NEBULA_METAD_SVC
              format: '{{`{{ .FQDN }}.cluster.local:{{ .Port }}`}}'
              joinWith: ","
      podSpec:
        securityContext:
          fsGroup: 1001
        containers:
          - name: nebula-storaged
            command:
              - /bin/bash
              - -c
              - |
                exec /usr/local/nebula/bin/nebula-storaged --flagfile=/usr/local/nebula/etc/nebula-storaged.conf --meta_server_addrs=$NEBULA_METAD_SVC --local_ip=$KB_POD_FQDN".cluster.local" --daemonize=false
            imagePullPolicy: {{default .Values.nebula.storaged.image.pullPolicy "IfNotPresent"}}
            ports:
            - containerPort: 9779
              name: thrift
              protocol: TCP
            - containerPort: 19779
              name: http
              protocol: TCP
            - containerPort: 19780
              name: http2
              protocol: TCP
            - containerPort: 9778
              name: admin
              protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /status
                port: http
                scheme: HTTP
              initialDelaySeconds: 10
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            volumeMounts:
              - mountPath: /usr/local/nebula/etc
                name: nebula-storaged
              - mountPath: /usr/local/nebula/data
                name: data
              - mountPath: /usr/local/nebula/logs
                name: logs
