apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-patroni-scripts
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  init_container.sh: |
    #!/bin/bash
    set -o errexit
    set -ex
    mkdir -p /home/postgres/pgdata/conf
    chmod +777 -R /home/postgres/pgdata/conf
    cp /home/postgres/conf/postgresql.conf /home/postgres/pgdata/conf
    chmod +777 /home/postgres/pgdata/conf/postgresql.conf
  prepare_patroni_yaml.py: |
    {{- .Files.Get "scripts/prepare-patroni-yaml.py" | nindent 4 }}
  pyjavaproperties.py : |
    {{- .Files.Get "scripts/py-java-properties.py" | nindent 4 }}
  setup.sh: |
    #!/bin/bash
    set -o errexit
    set -ex
    KB_PRIMARY_POD_NAME_PREFIX=${KB_PRIMARY_POD_NAME%%\.*}
    if [ "$KB_PRIMARY_POD_NAME_PREFIX" != "$KB_POD_NAME" ]; then
        sleep 3
    fi
    python3 /kb-scripts/prepare_patroni_yaml.py tmp_patroni.yaml
    export SPILO_CONFIGURATION=$(cat tmp_patroni.yaml)
    exec /launch.sh init