apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kb-rolebinding-{{ .Release.Namespace }}-{{ .Release.Name }}
  labels:
    {{ include "apecloud-mysql-cluster.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kb-role-{{ .Release.Namespace }}-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "apecloud-mysql-cluster.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
