apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connector.name" . }}-scripts
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "connector.labels" . | nindent 4 }}
data:
  connector-run.sh: |-
    {{- .Files.Get "scripts/connector-run.sh" | nindent 4 }}
  task-start.sh: |-
    {{- .Files.Get "scripts/task-start.sh.tpl" | nindent 4 }}