apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterVersion
metadata:
  name: ac-mysql-{{ default .Chart.AppVersion .Values.clusterVersionOverride }}
  annotations:
    kubeblocks.io/is-default-cluster-version: "false"
  labels:
    {{- include "apecloud-mysql.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: apecloud-mysql
  componentVersions:
  - componentDefRef: mysql
    versionsContext:
      containers:
      - name: mysql
        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ default .Values.image.pullPolicy "IfNotPresent" }}
    systemAccountSpec:
      cmdExecutorConfig:
        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
    switchoverSpec:
      cmdExecutorConfig:
        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
  - componentDefRef: vtcontroller
    versionsContext:
      containers:
        - name: etcd
          image: {{ .Values.wesqlscale.image.registry | default "docker.io" }}/{{ .Values.wesqlscale.image.repository }}:{{ .Values.wesqlscale.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.wesqlscale.image.pullPolicy }}
        - name: vtctld
          image: {{ .Values.wesqlscale.image.registry | default "docker.io" }}/{{ .Values.wesqlscale.image.repository }}:{{ .Values.wesqlscale.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.wesqlscale.image.pullPolicy }}
        - name: vtconsensus
          image: {{ .Values.wesqlscale.image.registry | default "docker.io" }}/{{ .Values.wesqlscale.image.repository }}:{{ .Values.wesqlscale.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.wesqlscale.image.pullPolicy }}
  - componentDefRef: vtgate
    versionsContext:
      containers:
        - name: vtgate
          image: {{ .Values.wesqlscale.image.registry | default "docker.io" }}/{{ .Values.wesqlscale.image.repository }}:{{ .Values.wesqlscale.image.tag }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.wesqlscale.image.pullPolicy }}
---

apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterVersion
metadata:
  name: ac-mysql-smartengine-{{ default .Chart.AppVersion .Values.clusterVersionOverride }}
  annotations:
    kubeblocks.io/is-default-cluster-version: "true"
  labels:
    {{- include "apecloud-mysql.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: apecloud-mysql
  componentVersions:
    - componentDefRef: mysql
      configSpecs:
        - name: mysql-consensusset-config
          templateRef: mysql8.0-smartengine-config-template
          constraintRef: mysql8.0-config-constraints
          volumeName: mysql-config
          namespace: {{ .Release.Namespace }}
      versionsContext:
        containers:
          - name: mysql
            image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.smartEngineTag }}
            imagePullPolicy: {{ default .Values.image.pullPolicy "IfNotPresent" }}
      systemAccountSpec:
        cmdExecutorConfig:
          image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.smartEngineTag }}
      switchoverSpec:
        cmdExecutorConfig:
          image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.repository }}:{{ .Values.image.smartEngineTag }}
    - componentDefRef: vtcontroller
      versionsContext:
        containers:
          - name: etcd
            image: {{ .Values.wesqlscale.image.registry | default "docker.io" }}/{{ .Values.wesqlscale.image.repository }}:{{ .Values.wesqlscale.image.tag }}
            imagePullPolicy: {{ default "IfNotPresent" .Values.wesqlscale.image.pullPolicy }}
          - name: vtctld
            image: {{ .Values.wesqlscale.image.registry | default "docker.io" }}/{{ .Values.wesqlscale.image.repository }}:{{ .Values.wesqlscale.image.tag }}
            imagePullPolicy: {{ default "IfNotPresent" .Values.wesqlscale.image.pullPolicy }}
          - name: vtconsensus
            image: {{ .Values.wesqlscale.image.registry | default "docker.io" }}/{{ .Values.wesqlscale.image.repository }}:{{ .Values.wesqlscale.image.tag }}
            imagePullPolicy: {{ default "IfNotPresent" .Values.wesqlscale.image.pullPolicy }}
    - componentDefRef: vtgate
      versionsContext:
        containers:
          - name: vtgate
            image: {{ .Values.wesqlscale.image.registry | default "docker.io" }}/{{ .Values.wesqlscale.image.repository }}:{{ .Values.wesqlscale.image.tag }}
            imagePullPolicy: {{ default "IfNotPresent" .Values.wesqlscale.image.pullPolicy }}