apiVersion: apps.kubeblocks.io/v1alpha1
kind: ClusterDefinition
metadata:
  name: diffusion
  labels:
    {{- include "llm.labels" . | nindent 4}}
spec:
  componentDefs:
    - name: diffusion
      workloadType: Stateful
      characterType: diffusion
      service:
        ports:
          - name: model
            port: 8000
            targetPort: model
      podSpec:
        containers:
          - name: diffusion
            imagePullPolicy: {{default .Values.image.pullPolicy "IfNotPresent"}}
            securityContext:
              runAsUser: 0
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            ports:
              - name: model
                containerPort: 8000
  connectionCredential:
    username: root
    password: ""