# permissions for end users to edit consensussets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consensusset-editor-role
rules:
- apiGroups:
  - dbaas.infracreate.com
  resources:
  - consensussets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dbaas.infracreate.com
  resources:
  - consensussets/status
  verbs:
  - get
