apiVersion: apps.kubeblocks.io/v1alpha1
kind: ServiceConnectionCredential
metadata:
  labels:
    app.kubernetes.io/name: serviceconnectioncredential
    app.kubernetes.io/instance: serviceconnectioncredential-sample
    app.kubernetes.io/part-of: kubeblocks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubeblocks
  name: serviceconnectioncredential-sample
spec:
  # TODO(user): Add fields here
