apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consensus-pod-patch
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "patch"]