apiVersion: dbaas.infracreate.com/v1alpha1
kind: Cluster
metadata:
  name: wesql
spec:
  appVersionRef: app-version-consensus
  clusterDefinitionRef: cluster-definition-consensus
  components:
    - name: wesql-css
      type: replicasets
      monitor: false
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            volumeMode: Filesystem