apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "postgresqlcluster.labels" . | nindent 4 }}
spec:
  clusterDefinitionRef: postgresql-ha # ref clusterdefinition.name
  clusterVersionRef: postgresql-{{ default .Chart.AppVersion .Values.clusterVersionOverride }} # ref clusterversion.name
  terminationPolicy: {{ .Values.terminationPolicy }}
  affinity:
    {{- with .Values.topologyKeys }}
    topologyKeys: {{ . | toYaml | nindent 6 }}
    {{- end }}
  {{- with $.Values.tolerations }}
  tolerations: {{ . | toYaml | nindent 4 }}
  {{- end }}
  componentSpecs:
    - name: postgresql # user-defined
      componentDefRef: postgresql-ha # ref clusterdefinition components.name
      customLabelSpecs:
        - key: apps.kubeblocks.postgresql.patroni/scope
          value: {{ .Release.Name }}-postgresql
          resources:
            - pattern: "v1/Pod"
              selector:
                app.kubernetes.io/managed-by: kubeblocks
            - pattern: "apps/v1/StatefulSet"
              selector:
                app.kubernetes.io/managed-by: kubeblocks
      monitor: {{ .Values.monitor.enabled | default false }}
      replicas: {{ .Values.replicaCount | default 2 }}
      primaryIndex: {{ .Values.primaryIndex | default 0 }}
      switchPolicy:
        type: {{ .Values.switchPolicy.type}}
      enabledLogs: {{ .Values.enabledLogs | toJson | indent 4 }}
      {{- with  .Values.resources }}
      resources:
        {{- with .limits }}
        limits:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
        {{- with .requests }}
        requests:
          cpu: {{ .cpu | quote }}
          memory: {{ .memory | quote }}
        {{- end }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumeClaimTemplates:
        - name: data # ref clusterdefinition components.containers.volumeMounts.name
          spec:
            storageClassName: {{ .Values.persistence.data.storageClassName }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.persistence.data.size }}
      {{- end }}

