# permissions for end users to view sysbenches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubebench.fullname" . }}-sysbench-viewer-role
  labels:
    {{- include "kubebench.labels" . | nindent 4 }}
rules:
- apiGroups:
  - benchmark.kubebench.io
  resources:
  - sysbenches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - benchmark.kubebench.io
  resources:
  - sysbenches/status
  verbs:
  - get
