apiVersion: apps.kubeblocks.io/v1alpha1
kind: Configuration
metadata:
  name: {{ include "kblib.clusterName" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels: {{ include "kblib.clusterLabels" . | nindent 4 }}
spec:
  clusterDefRef: apecloud-mysql
  clusterRef: {{ include "kblib.clusterName" . }}
  clusterVerRef: {{ .Values.version }}
  componentName: mysql
  configItemDetails:
    - name: mysql-consensusset-config
      {{- include "apecloud-mysql-cluster.userConfigTemplate" . | indent 6 }}
      {{- include "apecloud-mysql-cluster.userConfigurations" . | indent 6 }}